# TODO Use env specific config objects
LIVEDBPATH = 'live.db'
SECRET_KEY = 'changeme'
TEAM_NAME = 'CHANGEME'
TEAM_CAPACITY = 1.0
TEAM_REVENUE_CAP = 1
TEAM_DEVMAX = 1.0
TEAM_RESEARCH_MAX = 1.0
TEAM_COST = 1
RND_TAX_CREDIT = 0.25
